export const ASC = 'ASC';
export const DESC ='DESC';
export const PAGE_SIZE = 10;

export const ACTIONS = {
  SORT_PURCHASE : 'SORT_PURCHASE',
  CHANGE_SORT_BY : 'CHANGE_SORT_BY',
  SELECT_PURCHASE : 'SELECT_PURCHASE',
  SORT_BY_DATE : 'SORT_BY_DATE',
  RESET_SELECTED: 'RESET_SELECTED',
  CHANGE_PAGE: 'CHANGE_PAGE',
}
